import type { Heatmap } from './heatmap'
import { levelToCount } from './heatmap'

export interface ScriptConfig {
  repository: string
  branch: string
  minCommits: number
  maxCommits: number
  timezone: string
  authorName: string
  authorEmail: string
  commitPrefix: string
  skipExisting: boolean
  confirmPush: boolean
  heatmap: Heatmap
}

function shellQuote(value: string) {
  return `'${value.replace(/'/g, `'"'"'`)}'`
}

export function buildPlan(heatmap: Heatmap, min: number, max: number) {
  return Object.entries(heatmap)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([date, level]) => [date, levelToCount(level, min, max)] as const)
    .filter(([, count]) => count > 0)
}

export function generateScript(config: ScriptConfig) {
  const plan = buildPlan(config.heatmap, config.minCommits, config.maxCommits)
    .map(([date, count]) => `${date}|${count}`)
    .join('\n')

  return `#!/usr/bin/env bash
set -Eeuo pipefail

# Generated by GitHub Contribution Graph Generator.
# Nothing here contacts a server other than your own Git remote. Read it before running.

REPOSITORY_URL=${shellQuote(config.repository)}
TARGET_BRANCH=${shellQuote(config.branch)}
AUTHOR_NAME=${shellQuote(config.authorName)}
AUTHOR_EMAIL=${shellQuote(config.authorEmail)}
COMMIT_PREFIX=${shellQuote(config.commitPrefix)}
TIMEZONE_OFFSET=${shellQuote(config.timezone)}
SKIP_EXISTING=${config.skipExisting ? 'true' : 'false'}
CONFIRM_BEFORE_PUSH=${config.confirmPush ? 'true' : 'false'}

command -v git >/dev/null 2>&1 || {
  echo "Error: Git is required. Install it from https://git-scm.com/"
  exit 1
}

# Fall back to the machine's own Git identity, then ask.
[[ -n "$AUTHOR_NAME" ]]  || AUTHOR_NAME="$(git config --global user.name || true)"
[[ -n "$AUTHOR_EMAIL" ]] || AUTHOR_EMAIL="$(git config --global user.email || true)"
[[ -n "$AUTHOR_NAME" ]]  || read -r -p "Git author name: " AUTHOR_NAME
[[ -n "$AUTHOR_EMAIL" ]] || read -r -p "GitHub-linked author email: " AUTHOR_EMAIL

if [[ -z "$AUTHOR_NAME" || -z "$AUTHOR_EMAIL" ]]; then
  echo "Error: author name and a GitHub-linked email are required."
  exit 1
fi

task_base="\${TMPDIR:-/tmp}"
task_base="\${task_base%/}"
task_dir="$(mktemp -d "\${task_base}/github-contribution-graph.XXXXXX")"
repo_dir="\${task_dir}/repository"

cleanup() {
  status=$?
  if [[ $status -eq 0 && "$task_dir" == "\${task_base}/github-contribution-graph."* ]]; then
    rm -rf -- "$task_dir"
  else
    echo "Working copy kept at: $task_dir"
  fi
}
trap cleanup EXIT

echo "Cloning $REPOSITORY_URL"
git clone "$REPOSITORY_URL" "$repo_dir"
cd "$repo_dir"

if git show-ref --verify --quiet "refs/remotes/origin/$TARGET_BRANCH"; then
  git switch -C "$TARGET_BRANCH" "origin/$TARGET_BRANCH"
elif git rev-parse --verify HEAD >/dev/null 2>&1; then
  git switch -c "$TARGET_BRANCH"
else
  git symbolic-ref HEAD "refs/heads/$TARGET_BRANCH"
fi

git config user.name "$AUTHOR_NAME"
git config user.email "$AUTHOR_EMAIL"
git config commit.gpgSign false

existing_dates=""
if [[ "$SKIP_EXISTING" == "true" ]] && git rev-parse --verify HEAD >/dev/null 2>&1; then
  existing_dates="$(git log --all --format='%ae|%aI' \\
    | awk -F'|' -v email="$AUTHOR_EMAIL" '$1 == email { print substr($2, 1, 10) }' \\
    | sort -u)"
fi

created=0
skipped=0
while IFS='|' read -r day count; do
  [[ -z "$day" || "$count" -le 0 ]] && continue

  if [[ "$SKIP_EXISTING" == "true" ]] && grep -Fxq "$day" <<< "$existing_dates"; then
    skipped=$((skipped + 1))
    continue
  fi

  index=1
  while [[ $index -le $count ]]; do
    # Spread the day's commits across working hours so the history looks plausible.
    if [[ $count -eq 1 ]]; then
      hour=12
    else
      hour=$((9 + ((index - 1) * 10 / (count - 1))))
    fi
    minute=$(((index * 17 + count * 7) % 60))
    printf -v hour_padded '%02d' "$hour"
    printf -v minute_padded '%02d' "$minute"
    stamp="\${day}T\${hour_padded}:\${minute_padded}:00\${TIMEZONE_OFFSET}"
    message="\${COMMIT_PREFIX}: \${day} (\${index}/\${count})"

    GIT_AUTHOR_DATE="$stamp" GIT_COMMITTER_DATE="$stamp" \\
      git commit --allow-empty --quiet -m "$message"

    created=$((created + 1))
    index=$((index + 1))
  done
done <<'COMMIT_PLAN'
${plan}
COMMIT_PLAN

echo "Prepared $created commits; skipped $skipped existing dates."
echo "Target: $REPOSITORY_URL ($TARGET_BRANCH)"

if [[ $created -eq 0 ]]; then
  echo "Nothing to push."
  exit 0
fi

if [[ "$CONFIRM_BEFORE_PUSH" == "true" ]]; then
  read -r -p "Push these commits to GitHub? [y/N] " answer
  if [[ ! "$answer" =~ ^[Yy]$ ]]; then
    echo "Push cancelled."
    exit 2
  fi
fi

git push -u origin "$TARGET_BRANCH"
echo "Done. GitHub may take a few minutes to refresh the contribution graph."
`
}
